<?xml version="1.0" ?>
<robot name="tigra" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="length" value="1.85" />
<xacro:property name="width" value="0.75" />
<xacro:property name="heigth" value="0.6" />
<xacro:property name="mass" value="420" />

<xacro:property name="wheel_width" value="0.25" />
<xacro:property name="wheel_radius" value="0.25" />
<xacro:property name="wheel_mass" value="20" />
<xacro:property name="wheel_turn_limit" value="${pi/4}"/> 

<xacro:property name="wheelbase" value="1.24" />
<xacro:property name="trackbase" value="1.00" />
<xacro:property name="base_center" value="${length/2}" />

<!-- inertia -->
<xacro:macro name="null_inertial">
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.001" ixy="0" ixz="0"
               iyy="0.001" iyz="0"
               izz="0.001"/>
    </inertial>
</xacro:macro>

<xacro:macro name="base_inertial"
               params="width length height mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass * (width * width + height * height) / 12}"
               ixy="0" ixz="0"
               iyy="${mass * (length * length + height * height) / 12}"
               iyz="0"
               izz="${mass * (width * width + length * length) / 12}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="wheel_inertial"
               params="r h mass *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${mass}"/>
      <inertia ixx="${mass / 12 * (3 * r * r + h * h)}" ixy="0.0" ixz="0.0"
               iyy="${mass / 12 * (3 * r * r + h * h)}" iyz="0.0"
               izz="${mass / 2 * r * r}" />
    </inertial> 
</xacro:macro>
 
<!-- xacro base new -->
<link name="base_link">
<pose>0 0 0 0 0 0</pose>
    <visual>
     	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision name="base_collision">
    	<origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <box size="${length} ${width} ${heigth}"/>
        </geometry>
    </collision>
	<xacro:base_inertial
    width="${width}" length="${length}" 
	height="${heigth}" mass="${mass}" >
    <origin xyz="0 0 0" rpy="0 0 0" />
	</xacro:base_inertial>	
</link>


<!-- xacro wheel new -->
<xacro:macro name="wheels" params="name">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <xacro:wheel_inertial
          r="${wheel_radius}" h="${wheel_width}"
          mass="${wheel_mass}" >
	  <origin xyz="0 0 0" rpy="0 0 0" />
      </xacro:wheel_inertial>
    </link>
</xacro:macro>

<!-- zawarka solution -->
<xacro:macro name="speed_wheel" params="name base_name xyz ">
    <xacro:wheels name="wheel_${name}" />

    <link name="spring1_${name}">
      <xacro:null_inertial/>
    </link>

    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.000000001" upper="0.000000001" effort="0" velocity="0"/>
      <parent link="${base_name}"/>
      <child link="spring1_${name}"/>
      	<axis>
      		<dynamics>
      			<spring_stiffness>420000</spring_stiffness>
      			<spring_reference>1</spring_reference>
     			<damping>100000000</damping>
      			<friction>100</friction>
    		</dynamics>
    		<use_parent_model_frame>0</use_parent_model_frame>
  		</axis>
  		<physics>
    		<ode>
      			<implicit_spring_damper>1</implicit_spring_damper>
      			<cfm_damping>1</cfm_damping>
      				<limit>
        				<cfm>0</cfm>
        				<erp>0.2</erp>
      				</limit>
    		</ode>
  		</physics>
    </joint>

    <joint name="${name}_speed_joint" type="continuous">
      <parent link="spring1_${name}"/>
      <child link="wheel_${name}"/>
      <origin xyz="${xyz}" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="500.0" velocity="11.0" />
    </joint>
</xacro:macro>

<xacro:macro name="steer_wheel" params="name base_name xyz">
    <xacro:wheels name="wheel_${name}" />

    <link name="spring2_${name}">
      <xacro:null_inertial/>
    </link>

     <link name="steer_${name}">
      <xacro:null_inertial/>
    </link>

    <joint name="${name}_spring_joint" type="prismatic">
    <limit lower="-0.000000001" upper="0.000000001" effort="0" velocity="0"/>
      <parent link="${base_name}"/>
      <child link="spring2_${name}"/>
      	<axis>
      		<dynamics>
      			<spring_stiffness>420000</spring_stiffness>
      			<spring_reference>1</spring_reference>
     			<damping>100000000</damping>
      			<friction>100</friction>
    		</dynamics>
    		<use_parent_model_frame>0</use_parent_model_frame>
  		</axis>
  		<physics>
    		<ode>
      			<implicit_spring_damper>1</implicit_spring_damper>
      			<cfm_damping>1</cfm_damping>
      				<limit>
        				<cfm>0</cfm>
        				<erp>0.2</erp>
      				</limit>
    		</ode>
  		</physics>
    </joint>

    <joint name="${name}_steer_joint" type="revolute">
      <limit lower="${-wheel_turn_limit}"
             upper="${wheel_turn_limit}"
             effort="0" velocity="0"/>
      <parent link="spring2_${name}"/>
      <child link="steer_${name}"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      
    </joint>

    <joint name="${name}_speed_joint" type="continuous">
      <parent link="steer_${name}"/>
      <child link="wheel_${name}"/>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="500" velocity="11.0" />
    </joint>

</xacro:macro>

	<xacro:steer_wheel name="joint_right_wheel_1" base_name="base_link" xyz="0.5 -0.375 -0.3" />
	<xacro:steer_wheel name="joint_left_wheel_1" base_name="base_link" xyz="0.5 0.375 -0.3" />
	<xacro:speed_wheel name="joint_right_wheel_2" base_name="base_link" xyz="-0.5 -0.375 -0.3" />
	<xacro:speed_wheel name="joint_left_wheel_2" base_name="base_link" xyz="-0.55 0.375 -0.3" />
<!--<gazebo>
     <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
    </plugin> 

     Simulated vehicle interface 
    <plugin name="ModelPlugin" filename="librobot_gazebo.so" >
      <robotName>tigra</robotName>
      <wheelbase>base_link</wheelbase>
      <_joint>joint_right_wheel_2</_joint>
    </plugin>
</gazebo> -->

</robot>

